
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gtdc?autoReconnect=true&useSSL=false
    username: gtdc
    password: gtdc!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      physical_naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
